### ISSUE TITLE
Make the makefile just compile x86

### ISSUE THREAD

**Issue by powerjg** [darchr/microbench#2]
By default we want just x86 compiled. However, it would be useful if there were specific targets for ARM and RISC-V.

For instance,
```
make all-ARM
```

**Comment by hnpl** [comment]
Do we need a docker file to point to a specific version of gcc?

**Comment by powerjg** [comment]
See #3

**Comment by powerjg** [comment]
You may want to tackle both these issues at once. However, this issue is more important than the reproducible builds issue :).

**Comment by hnpl** [comment]
Solved!
